# Generated by Django 4.2.20 on 2025-04-18 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_currency",
                    models.CharField(
                        choices=[
                            ("BRL", "Brazilian Real"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("JPY", "Japanese Yen"),
                        ],
                        max_length=3,
                    ),
                ),
                ("source_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "target_currency",
                    models.CharField(
                        choices=[
                            ("BRL", "Brazilian Real"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("JPY", "Japanese Yen"),
                        ],
                        max_length=3,
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
