# Generated by Django 4.2.20 on 2025-04-19 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_currency",
                    models.CharField(
                        choices=[
                            ("BRL", "Brazilian Real"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("JPY", "Japanese Yen"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "target_currency",
                    models.CharField(
                        choices=[
                            ("BRL", "Brazilian Real"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("JPY", "Japanese Yen"),
                        ],
                        max_length=3,
                    ),
                ),
                ("base_rate", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "variation_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        help_text=(
                            "Percentage variation to trigger "
                            "notification (e.g., 5.00 = 5%)"
                        ),
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency Alert",
                "verbose_name_plural": "Currency Alerts",
                "ordering": ["-created_at"],
                "unique_together": {("user", "source_currency", "target_currency")},
            },
        ),
    ]
